
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 18 00:42:18 CET 2014
//----------------------------------------------------

package chevalier_muller;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int NEW = 10;
  public static final int TERM = 7;
  public static final int STRUCT = 5;
  public static final int EQUAL = 8;
  public static final int EOF = 0;
  public static final int POINT = 9;
  public static final int VAR = 2;
  public static final int PTR = 3;
  public static final int END_STRUCT = 6;
  public static final int error = 1;
  public static final int PRINT = 12;
  public static final int DOUBLE_QUOTE = 11;
  public static final int TEXT = 4;
}

