
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 15 13:46:15 CET 2014
//----------------------------------------------------

package chevalier_muller;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int END = 4;
  public static final int BEGIN = 3;
}

