
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 17 12:48:36 CET 2014
//----------------------------------------------------

package chevalier_muller;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int NEW = 11;
  public static final int TERM = 8;
  public static final int STRUCT = 6;
  public static final int EQUAL = 9;
  public static final int EOF = 0;
  public static final int POINT = 10;
  public static final int VALUE = 4;
  public static final int VAR = 2;
  public static final int PTR = 3;
  public static final int END_STRUCT = 7;
  public static final int error = 1;
  public static final int PRINT = 13;
  public static final int DOUBLE_QUOTE = 12;
  public static final int NAME = 5;
}

